// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAMaaAwYi8kvfCwxZxXW3tgTycBihcq6w',
    appId: '1:880862508290:android:9818b69296e87fd35a3e1b',
    messagingSenderId: '880862508290',
    projectId: 'meqdriver',
    storageBucket: 'meqdriver.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkuupzTTq8RrSodE23a0Dfly4aqunsX2U',
    appId: '1:880862508290:ios:f4540998d13161b95a3e1b',
    messagingSenderId: '880862508290',
    projectId: 'meqdriver',
    storageBucket: 'meqdriver.appspot.com',
    iosBundleId: 'com.example.getTransferDriver',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJJLLSqrt3PIB1o5t89e5Nq_Jtws6x14U',
    appId: '1:880862508290:web:3a76019260f181615a3e1b',
    messagingSenderId: '880862508290',
    projectId: 'meqdriver',
    authDomain: 'meqdriver.firebaseapp.com',
    storageBucket: 'meqdriver.appspot.com',
    measurementId: 'G-YPMTT4VW4F',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkuupzTTq8RrSodE23a0Dfly4aqunsX2U',
    appId: '1:880862508290:ios:f4540998d13161b95a3e1b',
    messagingSenderId: '880862508290',
    projectId: 'meqdriver',
    storageBucket: 'meqdriver.appspot.com',
    iosBundleId: 'com.example.getTransferDriver',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJJLLSqrt3PIB1o5t89e5Nq_Jtws6x14U',
    appId: '1:880862508290:web:6b906b29f22767975a3e1b',
    messagingSenderId: '880862508290',
    projectId: 'meqdriver',
    authDomain: 'meqdriver.firebaseapp.com',
    storageBucket: 'meqdriver.appspot.com',
    measurementId: 'G-9T3PCF82KJ',
  );

}